/* ================= 内容数据 =================
 * 新增单词只需改这个文件。字段说明：
 *   en   英文（朗读 + 显示）        zh  中文释义
 *   e    Emoji 图片                 s   例句（点 💬 朗读）
 *   q    游戏提问（可选，默认用主题的 q 模板，{w} 替换为 en）
 *   hex  颜色主题专用色值           shape/fill  形状主题专用
 *   n    数字主题的数量（详情页会显示 n 个 countEmoji）
 * 主题 id 用于保存进度，上线后不要改名。
 */
const GROUPS = [
  { id:'basics',  en:'First Words', zh:'认知启蒙' },
  { id:'animals', en:'Animal World', zh:'动物世界' },
  { id:'food',    en:'Yummy Food', zh:'好吃的' },
  { id:'me',      en:'Me & Family', zh:'我和家人' },
  { id:'daily',   en:'Everyday Life', zh:'生活日常' },
  { id:'world',   en:'Out & About', zh:'出行与自然' },
];

const THEMES = [
  /* ---------------- 认知启蒙 ---------------- */
  { id:'colors', group:'basics', en:'Colors', zh:'颜色', emoji:'🎨', c:'#FF6B8B', dark:'#E03A62', q:'Which one is {w}?', items:[
    {en:'red',zh:'红色',hex:'#F44336',s:'The apple is red.'},
    {en:'blue',zh:'蓝色',hex:'#2F80ED',s:'The sky is blue.'},
    {en:'yellow',zh:'黄色',hex:'#FFD426',s:'The banana is yellow.'},
    {en:'green',zh:'绿色',hex:'#3DBE5B',s:'The leaf is green.'},
    {en:'orange',zh:'橙色',hex:'#FF8A1F',s:'The orange is orange.'},
    {en:'purple',zh:'紫色',hex:'#9B51E0',s:'The grapes are purple.'},
    {en:'pink',zh:'粉色',hex:'#FF8FC2',s:'The pig is pink.'},
    {en:'brown',zh:'棕色',hex:'#8D5B3A',s:'The bear is brown.'},
    {en:'black',zh:'黑色',hex:'#222222',s:'The night is black.'},
    {en:'white',zh:'白色',hex:'#FFFFFF',s:'The snow is white.'},
    {en:'gray',zh:'灰色',hex:'#9E9E9E',s:'The elephant is gray.'},
  ]},
  { id:'numbers', group:'basics', en:'Numbers', zh:'数字', emoji:'🔢', c:'#29B6F6', dark:'#0B84C0', q:'Where is number {w}?', countEmoji:'🍎', items:[
    {en:'one',zh:'一',n:1,s:'I have one nose.'},
    {en:'two',zh:'二',n:2,s:'I have two eyes.'},
    {en:'three',zh:'三',n:3,s:'Three little pigs.'},
    {en:'four',zh:'四',n:4,s:'A car has four wheels.'},
    {en:'five',zh:'五',n:5,s:'I have five fingers.'},
    {en:'six',zh:'六',n:6,s:'Six little ducks.'},
    {en:'seven',zh:'七',n:7,s:'Seven days in a week.'},
    {en:'eight',zh:'八',n:8,s:'An octopus has eight arms.'},
    {en:'nine',zh:'九',n:9,s:'Nine little stars.'},
    {en:'ten',zh:'十',n:10,s:'I have ten toes.'},
  ]},
  { id:'shapes', group:'basics', en:'Shapes', zh:'形状', emoji:'🔷', c:'#26A69A', dark:'#00796B', q:'Where is the {w}?', items:[
    {en:'circle',zh:'圆形',shape:'circle',fill:'#FF7043',s:'The sun is a circle.'},
    {en:'square',zh:'正方形',shape:'square',fill:'#42A5F5',s:'The box is a square.'},
    {en:'triangle',zh:'三角形',shape:'triangle',fill:'#66BB6A',s:'A slice of pizza is a triangle.'},
    {en:'rectangle',zh:'长方形',shape:'rectangle',fill:'#AB47BC',s:'The door is a rectangle.'},
    {en:'oval',zh:'椭圆形',shape:'oval',fill:'#FFCA28',s:'An egg is an oval.'},
    {en:'star',zh:'星形',shape:'star',fill:'#FFB300',s:'Twinkle, twinkle, little star.'},
    {en:'heart',zh:'心形',shape:'heart',fill:'#EC407A',s:'I love you!'},
    {en:'diamond',zh:'菱形',shape:'diamond',fill:'#26C6DA',s:'The kite is a diamond.'},
  ]},

  /* ---------------- 动物世界 ---------------- */
  { id:'animals', group:'animals', en:'Animals', zh:'动物', emoji:'🐶', c:'#FFB547', dark:'#E08A00', q:'Where is the {w}?', items:[
    {en:'dog',zh:'小狗',e:'🐶',s:'The dog says woof woof!'},
    {en:'cat',zh:'小猫',e:'🐱',s:'The cat says meow!'},
    {en:'rabbit',zh:'兔子',e:'🐰',s:'The rabbit can jump.'},
    {en:'duck',zh:'鸭子',e:'🦆',s:'The duck says quack quack!'},
    {en:'chicken',zh:'小鸡',e:'🐔',s:'The chicken says cluck cluck!'},
    {en:'cow',zh:'奶牛',e:'🐮',s:'The cow says moo!'},
    {en:'pig',zh:'小猪',e:'🐷',s:'The pig says oink oink!'},
    {en:'sheep',zh:'绵羊',e:'🐑',s:'The sheep says baa!'},
    {en:'horse',zh:'马',e:'🐴',s:'The horse can run fast.'},
    {en:'frog',zh:'青蛙',e:'🐸',s:'The frog says ribbit!'},
    {en:'lion',zh:'狮子',e:'🦁',s:'The lion says roar!'},
    {en:'tiger',zh:'老虎',e:'🐯',s:'The tiger is strong.'},
    {en:'bear',zh:'熊',e:'🐻',s:'The bear likes honey.'},
    {en:'panda',zh:'熊猫',e:'🐼',s:'The panda eats bamboo.'},
    {en:'monkey',zh:'猴子',e:'🐵',s:'The monkey likes bananas.'},
    {en:'elephant',zh:'大象',e:'🐘',s:'The elephant is big.'},
    {en:'giraffe',zh:'长颈鹿',e:'🦒',s:'The giraffe is tall.'},
    {en:'zebra',zh:'斑马',e:'🦓',s:'The zebra has stripes.'},
  ]},
  { id:'ocean', group:'animals', en:'Ocean', zh:'海洋动物', emoji:'🐳', c:'#3D8BFD', dark:'#1A5FD0', q:'Where is the {w}?', items:[
    {en:'fish',zh:'鱼',e:'🐟',s:'The fish can swim.'},
    {en:'whale',zh:'鲸鱼',e:'🐳',s:'The whale is very big.'},
    {en:'dolphin',zh:'海豚',e:'🐬',s:'The dolphin can jump.'},
    {en:'shark',zh:'鲨鱼',e:'🦈',s:'The shark has sharp teeth.'},
    {en:'octopus',zh:'章鱼',e:'🐙',s:'The octopus has eight arms.'},
    {en:'squid',zh:'鱿鱼',e:'🦑',s:'The squid is long.'},
    {en:'crab',zh:'螃蟹',e:'🦀',s:'The crab walks sideways.'},
    {en:'lobster',zh:'龙虾',e:'🦞',s:'The lobster is red.'},
    {en:'shrimp',zh:'虾',e:'🦐',s:'The shrimp is small.'},
    {en:'turtle',zh:'海龟',e:'🐢',s:'The turtle is slow.'},
    {en:'penguin',zh:'企鹅',e:'🐧',s:'The penguin likes the cold.'},
    {en:'shell',zh:'贝壳',e:'🐚',s:'I find a shell on the beach.'},
  ]},
  { id:'bugs', group:'animals', en:'Bugs', zh:'小虫子', emoji:'🐞', c:'#8BC34A', dark:'#5A8F1C', q:'Where is the {w}?', items:[
    {en:'ant',zh:'蚂蚁',e:'🐜',s:'The ant is small but strong.'},
    {en:'bee',zh:'蜜蜂',e:'🐝',s:'The bee says buzz buzz!'},
    {en:'butterfly',zh:'蝴蝶',e:'🦋',s:'The butterfly is pretty.'},
    {en:'ladybug',zh:'瓢虫',e:'🐞',s:'The ladybug has spots.'},
    {en:'caterpillar',zh:'毛毛虫',e:'🐛',s:'The caterpillar is hungry.'},
    {en:'snail',zh:'蜗牛',e:'🐌',s:'The snail is slow.'},
    {en:'spider',zh:'蜘蛛',e:'🕷️',s:'The spider has eight legs.'},
    {en:'cricket',zh:'蟋蟀',e:'🦗',s:'The cricket sings at night.'},
    {en:'mosquito',zh:'蚊子',e:'🦟',s:'The mosquito says bzzz.'},
    {en:'worm',zh:'虫子',e:'🪱',s:'The worm lives in the ground.'},
  ]},

  /* ---------------- 好吃的 ---------------- */
  { id:'fruits', group:'food', en:'Fruits', zh:'水果', emoji:'🍎', c:'#5DC47A', dark:'#2E9A4C', q:'Where is the {w}?', items:[
    {en:'apple',zh:'苹果',e:'🍎',s:'I like apples.'},
    {en:'banana',zh:'香蕉',e:'🍌',s:'I like bananas.'},
    {en:'orange',zh:'橙子',e:'🍊',s:'I like oranges.'},
    {en:'grapes',zh:'葡萄',e:'🍇',s:'I like grapes.',q:'Where are the grapes?'},
    {en:'strawberry',zh:'草莓',e:'🍓',s:'I like strawberries.'},
    {en:'watermelon',zh:'西瓜',e:'🍉',s:'I like watermelon.'},
    {en:'pear',zh:'梨',e:'🍐',s:'I like pears.'},
    {en:'peach',zh:'桃子',e:'🍑',s:'I like peaches.'},
    {en:'cherry',zh:'樱桃',e:'🍒',s:'I like cherries.'},
    {en:'pineapple',zh:'菠萝',e:'🍍',s:'I like pineapples.'},
    {en:'mango',zh:'芒果',e:'🥭',s:'I like mangoes.'},
    {en:'lemon',zh:'柠檬',e:'🍋',s:'The lemon is sour.'},
    {en:'kiwi',zh:'猕猴桃',e:'🥝',s:'The kiwi is green inside.'},
    {en:'coconut',zh:'椰子',e:'🥥',s:'The coconut is hard.'},
  ]},
  { id:'veggies', group:'food', en:'Vegetables', zh:'蔬菜', emoji:'🥕', c:'#FF9F43', dark:'#D9720F', q:'Where is the {w}?', items:[
    {en:'carrot',zh:'胡萝卜',e:'🥕',s:'Rabbits like carrots.'},
    {en:'tomato',zh:'西红柿',e:'🍅',s:'The tomato is red.'},
    {en:'potato',zh:'土豆',e:'🥔',s:'I like potatoes.'},
    {en:'corn',zh:'玉米',e:'🌽',s:'The corn is yellow.'},
    {en:'broccoli',zh:'西兰花',e:'🥦',s:'Broccoli looks like a tree.'},
    {en:'cucumber',zh:'黄瓜',e:'🥒',s:'The cucumber is green.'},
    {en:'mushroom',zh:'蘑菇',e:'🍄',s:'The mushroom has a hat.'},
    {en:'onion',zh:'洋葱',e:'🧅',s:'The onion makes me cry.'},
    {en:'garlic',zh:'大蒜',e:'🧄',s:'The garlic is white.'},
    {en:'pepper',zh:'辣椒',e:'🌶️',s:'The pepper is hot!'},
    {en:'lettuce',zh:'生菜',e:'🥬',s:'I eat lettuce.'},
    {en:'sweet potato',zh:'红薯',e:'🍠',s:'The sweet potato is sweet.'},
  ]},
  { id:'food', group:'food', en:'Food', zh:'食物', emoji:'🍞', c:'#F4A261', dark:'#C9702A', q:'Where is the {w}?', items:[
    {en:'bread',zh:'面包',e:'🍞',s:'I eat bread for breakfast.'},
    {en:'rice',zh:'米饭',e:'🍚',s:'I eat rice.'},
    {en:'noodles',zh:'面条',e:'🍜',s:'I like noodles.',q:'Where are the noodles?'},
    {en:'dumplings',zh:'饺子',e:'🥟',s:'I like dumplings.',q:'Where are the dumplings?'},
    {en:'egg',zh:'鸡蛋',e:'🥚',s:'I eat an egg.',q:'Where is the egg?'},
    {en:'milk',zh:'牛奶',e:'🥛',s:'I drink milk.'},
    {en:'water',zh:'水',e:'💧',s:'I drink water.'},
    {en:'juice',zh:'果汁',e:'🧃',s:'I drink juice.'},
    {en:'cake',zh:'蛋糕',e:'🍰',s:'Happy birthday! Here is a cake.'},
    {en:'cookie',zh:'饼干',e:'🍪',s:'I want a cookie.'},
    {en:'ice cream',zh:'冰淇淋',e:'🍦',s:'The ice cream is cold.'},
    {en:'pizza',zh:'披萨',e:'🍕',s:'I like pizza.'},
    {en:'hamburger',zh:'汉堡',e:'🍔',s:'The hamburger is big.'},
    {en:'candy',zh:'糖果',e:'🍬',s:'The candy is sweet.'},
  ]},

  /* ---------------- 我和家人 ---------------- */
  { id:'body', group:'me', en:'My Body', zh:'身体部位', emoji:'🙋', c:'#4FB6F0', dark:'#1B86C4', q:'Where is the {w}?', items:[
    {en:'face',zh:'脸',e:'🙂',s:'Wash your face!'},
    {en:'eye',zh:'眼睛',e:'👁️',s:'I see with my eyes.'},
    {en:'ear',zh:'耳朵',e:'👂',s:'I hear with my ears.'},
    {en:'nose',zh:'鼻子',e:'👃',s:'I smell with my nose.'},
    {en:'mouth',zh:'嘴巴',e:'👄',s:'I eat with my mouth.'},
    {en:'tooth',zh:'牙齿',e:'🦷',s:'Brush your teeth!'},
    {en:'tongue',zh:'舌头',e:'👅',s:'Stick out your tongue!'},
    {en:'hand',zh:'手',e:'✋',s:'Clap your hands!'},
    {en:'finger',zh:'手指',e:'☝️',s:'I have ten fingers.'},
    {en:'arm',zh:'手臂',e:'💪',s:'Wave your arms!'},
    {en:'leg',zh:'腿',e:'🦵',s:'Shake your legs!'},
    {en:'foot',zh:'脚',e:'🦶',s:'Stamp your feet!'},
  ]},
  { id:'family', group:'me', en:'Family', zh:'家人', emoji:'👨‍👩‍👧', c:'#A48BFF', dark:'#7454F0', q:'Where is the {w}?', items:[
    {en:'Daddy',zh:'爸爸',e:'👨',s:'I love you, Daddy!',q:'Where is Daddy?'},
    {en:'Mommy',zh:'妈妈',e:'👩',s:'I love you, Mommy!',q:'Where is Mommy?'},
    {en:'Grandpa',zh:'爷爷 / 外公',e:'👴',s:'Hello, Grandpa!',q:'Where is Grandpa?'},
    {en:'Grandma',zh:'奶奶 / 外婆',e:'👵',s:'Hello, Grandma!',q:'Where is Grandma?'},
    {en:'brother',zh:'哥哥 / 弟弟',e:'👦',s:'This is my brother.'},
    {en:'sister',zh:'姐姐 / 妹妹',e:'👧',s:'This is my sister.'},
    {en:'baby',zh:'宝宝',e:'👶',s:'The baby is sleeping.'},
    {en:'me',zh:'我',e:'🙋',s:'This is me!',q:'Which one is me?'},
    {en:'family',zh:'一家人',e:'👨‍👩‍👧‍👦',s:'I love my family!'},
  ]},
  { id:'feelings', group:'me', en:'Feelings', zh:'心情', emoji:'😊', c:'#FFC93C', dark:'#D39A00', q:'Who is {w}?', items:[
    {en:'happy',zh:'开心',e:'😀',s:'I am happy!'},
    {en:'sad',zh:'难过',e:'😢',s:'I am sad.'},
    {en:'angry',zh:'生气',e:'😠',s:'I am angry!'},
    {en:'scared',zh:'害怕',e:'😨',s:'I am scared.'},
    {en:'surprised',zh:'惊讶',e:'😮',s:'Wow! I am surprised!'},
    {en:'excited',zh:'兴奋',e:'🤩',s:'I am so excited!'},
    {en:'sleepy',zh:'困了',e:'😴',s:'I am sleepy. Good night!'},
    {en:'tired',zh:'累了',e:'🥱',s:'I am tired.'},
    {en:'sick',zh:'生病',e:'🤒',s:'I am sick.'},
    {en:'silly',zh:'调皮',e:'🤪',s:'I am silly!'},
  ]},
  { id:'actions', group:'me', en:'Actions', zh:'动作', emoji:'🏃', c:'#EF5350', dark:'#C62828', q:'Who can {w}?', items:[
    {en:'run',zh:'跑',e:'🏃',s:'I can run fast.',q:'Who is running?'},
    {en:'walk',zh:'走',e:'🚶',s:'Let\'s walk together.',q:'Who is walking?'},
    {en:'swim',zh:'游泳',e:'🏊',s:'I can swim.',q:'Who is swimming?'},
    {en:'dance',zh:'跳舞',e:'💃',s:'Let\'s dance!',q:'Who is dancing?'},
    {en:'sing',zh:'唱歌',e:'🎤',s:'Let\'s sing a song!',q:'Which one is sing?'},
    {en:'climb',zh:'攀爬',e:'🧗',s:'I can climb.',q:'Who is climbing?'},
    {en:'ride a bike',zh:'骑车',e:'🚴',s:'I can ride a bike.',q:'Who is riding a bike?'},
    {en:'sleep',zh:'睡觉',e:'🛌',s:'Time to sleep.',q:'Who is sleeping?'},
    {en:'read',zh:'读书',e:'📖',s:'Let\'s read a book.',q:'Which one is read?'},
    {en:'draw',zh:'画画',e:'🖍️',s:'I can draw a cat.',q:'Which one is draw?'},
    {en:'clap',zh:'拍手',e:'👏',s:'Clap, clap, clap!',q:'Which one is clap?'},
    {en:'wave',zh:'挥手',e:'👋',s:'Wave bye-bye!',q:'Which one is wave?'},
  ]},
  { id:'clothes', group:'me', en:'Clothes', zh:'衣服', emoji:'👕', c:'#EC6FB8', dark:'#C13F8C', q:'Where is the {w}?', items:[
    {en:'T-shirt',zh:'T恤',e:'👕',s:'Put on your T-shirt.'},
    {en:'dress',zh:'裙子',e:'👗',s:'What a pretty dress!'},
    {en:'pants',zh:'裤子',e:'👖',s:'Put on your pants.',q:'Where are the pants?'},
    {en:'shorts',zh:'短裤',e:'🩳',s:'It\'s hot. Wear shorts.',q:'Where are the shorts?'},
    {en:'coat',zh:'外套',e:'🧥',s:'It\'s cold. Wear a coat.'},
    {en:'hat',zh:'帽子',e:'👒',s:'I wear a hat.'},
    {en:'cap',zh:'鸭舌帽',e:'🧢',s:'I like my blue cap.'},
    {en:'shoes',zh:'鞋子',e:'👟',s:'Put on your shoes.',q:'Where are the shoes?'},
    {en:'socks',zh:'袜子',e:'🧦',s:'Put on your socks.',q:'Where are the socks?'},
    {en:'gloves',zh:'手套',e:'🧤',s:'My gloves keep me warm.',q:'Where are the gloves?'},
    {en:'scarf',zh:'围巾',e:'🧣',s:'My scarf is warm.'},
    {en:'glasses',zh:'眼镜',e:'👓',s:'Grandpa wears glasses.',q:'Where are the glasses?'},
  ]},

  /* ---------------- 生活日常 ---------------- */
  { id:'home', group:'daily', en:'My Home', zh:'家里', emoji:'🏠', c:'#FF8C69', dark:'#D45A35', q:'Where is the {w}?', items:[
    {en:'house',zh:'房子',e:'🏠',s:'This is my house.'},
    {en:'door',zh:'门',e:'🚪',s:'Open the door, please.'},
    {en:'bed',zh:'床',e:'🛏️',s:'Time for bed.'},
    {en:'chair',zh:'椅子',e:'🪑',s:'Sit on the chair.'},
    {en:'sofa',zh:'沙发',e:'🛋️',s:'The sofa is soft.'},
    {en:'TV',zh:'电视',e:'📺',s:'Turn off the TV.'},
    {en:'light',zh:'灯',e:'💡',s:'Turn on the light.'},
    {en:'clock',zh:'钟',e:'⏰',s:'The clock says tick tock.'},
    {en:'phone',zh:'手机',e:'📱',s:'Mommy is on the phone.'},
    {en:'cup',zh:'杯子',e:'☕',s:'This is my cup.'},
    {en:'spoon',zh:'勺子',e:'🥄',s:'I eat with a spoon.'},
    {en:'bathtub',zh:'浴缸',e:'🛁',s:'Bath time!'},
  ]},
  { id:'toys', group:'daily', en:'Toys', zh:'玩具', emoji:'🧸', c:'#FF7EB3', dark:'#D6477F', q:'Where is the {w}?', items:[
    {en:'ball',zh:'球',e:'⚽',s:'Kick the ball!'},
    {en:'teddy bear',zh:'泰迪熊',e:'🧸',s:'I hug my teddy bear.'},
    {en:'balloon',zh:'气球',e:'🎈',s:'The balloon goes up.'},
    {en:'kite',zh:'风筝',e:'🪁',s:'Let\'s fly a kite!'},
    {en:'robot',zh:'机器人',e:'🤖',s:'The robot can talk.'},
    {en:'puzzle',zh:'拼图',e:'🧩',s:'Let\'s do a puzzle.'},
    {en:'yo-yo',zh:'溜溜球',e:'🪀',s:'Up and down goes the yo-yo.'},
    {en:'toy train',zh:'玩具火车',e:'🚂',s:'Choo choo! Here comes the train.'},
    {en:'drum',zh:'鼓',e:'🥁',s:'Boom boom goes the drum.'},
    {en:'guitar',zh:'吉他',e:'🎸',s:'I can play the guitar.'},
    {en:'piano',zh:'钢琴',e:'🎹',s:'I can play the piano.'},
    {en:'trumpet',zh:'小号',e:'🎺',s:'Toot toot goes the trumpet.'},
  ]},
  { id:'school', group:'daily', en:'School', zh:'学校', emoji:'🎒', c:'#5C9DFF', dark:'#2F6FD6', q:'Where is the {w}?', items:[
    {en:'school bag',zh:'书包',e:'🎒',s:'This is my school bag.'},
    {en:'book',zh:'书',e:'📖',s:'I like to read books.'},
    {en:'notebook',zh:'笔记本',e:'📒',s:'Open your notebook.'},
    {en:'pencil',zh:'铅笔',e:'✏️',s:'I write with a pencil.'},
    {en:'pen',zh:'钢笔',e:'🖊️',s:'This is a pen.'},
    {en:'crayon',zh:'蜡笔',e:'🖍️',s:'I draw with a crayon.'},
    {en:'paints',zh:'颜料',e:'🎨',s:'Let\'s paint a picture!',q:'Where are the paints?'},
    {en:'scissors',zh:'剪刀',e:'✂️',s:'Be careful with scissors.',q:'Where are the scissors?'},
    {en:'ruler',zh:'尺子',e:'📏',s:'The ruler is long.'},
    {en:'computer',zh:'电脑',e:'💻',s:'This is a computer.'},
  ]},
  { id:'jobs', group:'daily', en:'Jobs', zh:'职业', emoji:'👩‍⚕️', c:'#7E8CE0', dark:'#4C5BC0', q:'Who is the {w}?', items:[
    {en:'doctor',zh:'医生',e:'🧑‍⚕️',s:'The doctor helps sick people.'},
    {en:'teacher',zh:'老师',e:'🧑‍🏫',s:'Good morning, teacher!'},
    {en:'police officer',zh:'警察',e:'👮',s:'The police officer keeps us safe.'},
    {en:'firefighter',zh:'消防员',e:'🧑‍🚒',s:'The firefighter puts out fires.'},
    {en:'cook',zh:'厨师',e:'🧑‍🍳',s:'The cook makes yummy food.'},
    {en:'farmer',zh:'农民',e:'🧑‍🌾',s:'The farmer grows vegetables.'},
    {en:'builder',zh:'建筑工人',e:'👷',s:'The builder builds houses.'},
    {en:'pilot',zh:'飞行员',e:'🧑‍✈️',s:'The pilot flies a plane.'},
    {en:'astronaut',zh:'宇航员',e:'🧑‍🚀',s:'The astronaut goes to space.'},
    {en:'scientist',zh:'科学家',e:'🧑‍🔬',s:'The scientist does experiments.'},
    {en:'artist',zh:'画家',e:'🧑‍🎨',s:'The artist paints pictures.'},
    {en:'singer',zh:'歌手',e:'🧑‍🎤',s:'The singer sings songs.'},
  ]},

  /* ---------------- 出行与自然 ---------------- */
  { id:'cars', group:'world', en:'Cars', zh:'汽车', emoji:'🚗', c:'#FF7F50', dark:'#E0501C', q:'Where is the {w}?', items:[
    {en:'car',zh:'小汽车',e:'🚗',s:'Beep beep! A car!'},
    {en:'bus',zh:'公交车',e:'🚌',s:'The bus is big.'},
    {en:'taxi',zh:'出租车',e:'🚕',s:'The taxi is yellow.'},
    {en:'jeep',zh:'越野车',e:'🚙',s:'The jeep can go up the hill.'},
    {en:'van',zh:'面包车',e:'🚐',s:'We go to school in a van.'},
    {en:'truck',zh:'卡车',e:'🚚',s:'The truck is heavy.'},
    {en:'big truck',zh:'大货车',e:'🚛',s:'The big truck is very long.'},
    {en:'fire truck',zh:'消防车',e:'🚒',s:'The fire truck is red.'},
    {en:'police car',zh:'警车',e:'🚓',s:'Wee woo! A police car!'},
    {en:'ambulance',zh:'救护车',e:'🚑',s:'The ambulance helps people.'},
    {en:'tractor',zh:'拖拉机',e:'🚜',s:'The tractor is on the farm.'},
    {en:'race car',zh:'赛车',e:'🏎️',s:'The race car is fast!'},
  ]},
  { id:'transport', group:'world', en:'Transport', zh:'交通工具', emoji:'✈️', c:'#00B8D4', dark:'#00838F', q:'Where is the {w}?', items:[
    {en:'train',zh:'火车',e:'🚆',s:'The train is long.'},
    {en:'fast train',zh:'高铁',e:'🚄',s:'The fast train is very fast.'},
    {en:'subway',zh:'地铁',e:'🚇',s:'The subway goes under the ground.'},
    {en:'airplane',zh:'飞机',e:'✈️',s:'The airplane flies in the sky.'},
    {en:'helicopter',zh:'直升机',e:'🚁',s:'The helicopter goes up and down.'},
    {en:'rocket',zh:'火箭',e:'🚀',s:'The rocket goes to the moon.'},
    {en:'boat',zh:'小船',e:'⛵',s:'The boat is on the water.'},
    {en:'ship',zh:'轮船',e:'🚢',s:'The ship is very big.'},
    {en:'canoe',zh:'独木舟',e:'🛶',s:'Row, row, row the canoe.'},
    {en:'bike',zh:'自行车',e:'🚲',s:'I ride my bike.'},
    {en:'motorcycle',zh:'摩托车',e:'🏍️',s:'The motorcycle is loud.'},
    {en:'scooter',zh:'滑板车',e:'🛴',s:'I ride my scooter.'},
  ]},
  { id:'weather', group:'world', en:'Weather', zh:'天气', emoji:'🌦️', c:'#64B5F6', dark:'#1E88E5', q:'Which one is {w}?', items:[
    {en:'sunny',zh:'晴天',e:'☀️',s:'It\'s sunny today.'},
    {en:'cloudy',zh:'多云',e:'☁️',s:'It\'s cloudy today.'},
    {en:'rainy',zh:'下雨',e:'🌧️',s:'It\'s rainy. Take an umbrella.'},
    {en:'snowy',zh:'下雪',e:'🌨️',s:'It\'s snowy. Let\'s make a snowman!'},
    {en:'windy',zh:'刮风',e:'🌬️',s:'It\'s windy today.'},
    {en:'stormy',zh:'雷雨',e:'⛈️',s:'It\'s stormy. Stay inside.'},
    {en:'foggy',zh:'有雾',e:'🌫️',s:'It\'s foggy. I can\'t see.'},
    {en:'rainbow',zh:'彩虹',e:'🌈',s:'Look! A rainbow!',q:'Where is the rainbow?'},
    {en:'hot',zh:'热',e:'🥵',s:'It\'s hot today.',q:'Who is hot?'},
    {en:'cold',zh:'冷',e:'🥶',s:'It\'s cold today.',q:'Who is cold?'},
  ]},
  { id:'nature', group:'world', en:'Nature', zh:'大自然', emoji:'🌳', c:'#43A047', dark:'#2E7D32', q:'Where is the {w}?', items:[
    {en:'sun',zh:'太阳',e:'🌞',s:'Good morning, sun!'},
    {en:'moon',zh:'月亮',e:'🌙',s:'Good night, moon.'},
    {en:'star',zh:'星星',e:'🌟',s:'The stars are shining.'},
    {en:'earth',zh:'地球',e:'🌍',s:'We live on the earth.'},
    {en:'tree',zh:'树',e:'🌳',s:'The tree is tall.'},
    {en:'flower',zh:'花',e:'🌸',s:'The flower smells nice.'},
    {en:'leaf',zh:'叶子',e:'🍁',s:'The leaf falls down.'},
    {en:'grass',zh:'草',e:'🌿',s:'The grass is green.'},
    {en:'cactus',zh:'仙人掌',e:'🌵',s:'The cactus is spiky.'},
    {en:'mountain',zh:'山',e:'⛰️',s:'The mountain is high.'},
    {en:'sea',zh:'大海',e:'🌊',s:'The sea is blue.'},
    {en:'island',zh:'小岛',e:'🏝️',s:'There is a tree on the island.'},
  ]},
];

// 形状主题用的 SVG（viewBox 0 0 100 100）
const SHAPES = {
  circle:    '<circle cx="50" cy="50" r="42"/>',
  square:    '<rect x="12" y="12" width="76" height="76" rx="6"/>',
  triangle:  '<polygon points="50,10 93,86 7,86" stroke-linejoin="round"/>',
  rectangle: '<rect x="4" y="26" width="92" height="48" rx="6"/>',
  oval:      '<ellipse cx="50" cy="50" rx="46" ry="30"/>',
  star:      '<polygon points="50,6 61,38 95,38 67,58 78,91 50,71 22,91 33,58 5,38 39,38"/>',
  heart:     '<path d="M50 88C20 66 6 50 6 32 6 18 17 8 30 8c9 0 16 5 20 12 4-7 11-12 20-12 13 0 24 10 24 24 0 18-14 34-44 56z"/>',
  diamond:   '<polygon points="50,4 90,50 50,96 10,50"/>',
};
